# Generated by Django 5.2.2 on 2025-07-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_type_notification_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date']},
        ),
    ]
